name: "pzem-004 to mqtt"
description: "Fetch data from pzem 004"
version: "0.0.5"
url: "https://github.com/Daniel-Hope/hassio-pzem004"
slug: "pzem-004_to_mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
schema:
  serial: str?
  mqtt:
    broker: str?
    username: str?
    password: str?
options:
  serial: "/dev/ttyUSB0"
devices:
  - "/dev/ttyUSB0:/dev/ttyUSB0:rwm"
services:
  - "mqtt:need"
